filename: "mock_{{.InterfaceName}}.go"
dir: "pkg/mocks/{{.InterfaceDirRelative}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
all: True
disable-version-string: True
with-expecter: True
packages:
  github.com/arielsrv/sdk-cli:
    config:
      recursive: True
log-level: Warn
